# Generated by Django 3.2.7 on 2021-10-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='algo_private_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
