# Generated by Django 3.2.8 on 2021-11-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20211028_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_pic',
            field=models.ImageField(blank=True, default='id.png', null=True, upload_to=''),
        ),
    ]
